valueFilePath: "/charts/prometheus/values.yaml"
repoURL: "https://git.example.com/org/value-files.git"
targetRevision: dev
ref: values

cluster:
  secret:
    enabled: true # If false add your own cluster secrets
clusters:
  kubernetes: 
    name: kubernetes
    server: https://172.30.1.2:6443
    caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUU1GblRQeUtYTVl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBM01ETXhPREk1TkRkYUZ3MHpOREEzTURFeE9ETTBORGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM1Tm92c1pnYW0vbSsxMXM1eklhSStnWTVqSVdkTnArZjdzZmEvMndGVjVVVzhTMlFEWkxrM3hrbjkKcWh4R2NTU3JyYzl0c3oybFRuT0orL28xTDdDZlo4V1gzVkRxaEwwRGgxYVgxOUxxeEwvY0x6MVZPU2N2SGtpRQoxdVdZRWE0dkRkelEreGdNcjNOSU1nYndnelhjTGd5Sm80L3lPTlk0RThtTm5CbGluNlpjd3lRZWc5UHpXR3BkCkNCbXdBN3E0cDJWMDBQQUdCVXlLdlNvaWFMWVNINVpWQ0h6MlY3Y1R0WGRNL1NQMGM1UEFtRVREU2U2VENGZ0wKbUpnbWkyMEV3UFdhOS9wdzBrck40NlF1cGlxUmQwYXhrRXRuS2xGczhUcks1VTdEamtaVzkxT2E1bGF2d0t6UwowQXJUdGViOEdpWlpOWUd0NDBEdW5JVzBZaFk5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUa3UvRUEyYjFkYVk5RWNrdVhHV3poRXRZME9EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ29YVWV0NW5QVwo0MXZ0Yy9rdllZaXI4dVNhS3VkMG9JU3ZHL0ppRDM4RnR2MGdzeXNQY0xVM214elNkcTVuMTZWb2N6THhPaFYvCkN6U0hlZlJoUFZiTzdqU2JDbmhGS3lpWXZndXM3OHN1ZExZR3h0NEVsR0xjZ3dXS1NycU9mQzBBZjJ4RXpJaHkKQ1ErOFpqQlo3WVRnVWV1b1hFKzhrK3RzY0d3TzgzbkRMTi9zYXFOMisrTmRlVVJRekQyM3hvWWNHQWdJUSszLwpXOW9VZzg5bTM2dXd5V1JIcnEzOFBrVVplL054dXZITUtDRVRJcFFJYWUrM3JTVE1NQ0N5ZlNtUVpHNGhQMDFYCjBEcVdCNkljcnI3cEhJWmVHRXVzU3N3d09DRXp0aUZoOHlzZHV2dFFoYjQ3Yjcyc25HRlJIdFhOUkR3QlZPMHcKS3ZJVTBzN3A5SGJiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IktZNTk2Y0FvcXhzcUNfelp4Zk5nY0NvT2pxUlJOaTNJU1BSQUo1ZEo5UTgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzIxNTYwOTk3LCJpYXQiOjE3MjE1NTczOTcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMGEyYmU3MDUtMDRkZi00NmY5LTljZWQtYzk0N2RlMmM0MGFkIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhcmdvY2QtbWFuYWdlciIsInVpZCI6IjJiMWM4NWNkLTAyN2MtNGIzZS05YTI4LTM5Yzk4ODI2OTI0ZSJ9fSwibmJmIjoxNzIxNTU3Mzk3LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YXJnb2NkLW1hbmFnZXIifQ.QU2UKhT6oF-lB6c9VvR6PwPsnVtxhvq2hKJ9u8Nwk33yF8whvdW3SCtGFFg4jmZDczhN_YzZht3cAWSxXxQPTSy2-IZVcusBN7tP8lmbB49UpSR-96KJd3mFVD-sjTRcVmfHeC-yx-8AybGHKBKpiqK0QZNhWHKi-CQA3zsreutEAHyMYkdmine1xEbw-lfQXrJnXKVl_2TeACAm3fNMD-BVCZxhsjqr7PRrHXps9Ef7hw6LkaBNsXs-srknvcprpIUIfCGNtXH0HjGidVd4uIBFbNh0XR9hFl_doBFq0jm_sulKMX80O8l-q12mkD3YtZSi-rZfBzeLvWn0wn_cjg
    insecure: false
gitrepo:
  secret:
    enabled: true # If false add your own git secrets
gitrepos:
#   naren4b:
#     name: naren4b
#     url: https://github.com/naren4b
#     username: naren4b
#     password: ""
