{{if .Values.cluster.secret.enabled }}
{{- range $key, $value := .Values.clusters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.name }}-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: {{ $value.name }}
  server: {{ $value.server }}
  config: |
    {
      "bearerToken": "{{ $value.token }}",
      "tlsClientConfig": {
        "insecure": {{ $value.insecure }},
        "caData": "{{ $value.caData }}"
      }
    }
---
{{- end }}
{{- end }}