{{ if .Values.applicationSet.myapp.enable  }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-applicationset
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{ "{{" }}name{{ "}}" }}-my-app'
    spec:
      source:
        repoURL: 'https://github.com/naren4b/argo-cd.git'
        targetRevision: 'HEAD'
        path: charts/my-app
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
         syncOptions:
          - CreateNamespace=true
{{ end}}