{{- range $key, $value := .Values.gitrepos }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $value.name }}-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ $value.url }}
  username: {{ $value.username }}
  password: {{ $value.token }}
---
{{- end }}
