apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: zone-argocd-applicationset
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{ "{{" }}name{{ "}}" }}-zone-argocd'
    spec:
      project: "default"
      source:
        chart: argo-cd
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 7.3.8
        helm:
          releaseName: argo-cd
      destination:
        server: '{{ "{{" }}server{{ "}}" }}'
