apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: in-cluster-zone-argocd-applicationset
  namespace: in-cluster-zone-argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{ "{{" }}name{{ "}}" }}-zone-argocd'
    spec:
      project: "default"
      sources:
      - repoURL: 'https://github.com/naren4b/argo-cd.git'
        targetRevision: HEAD
        path: charts/zone-argocd
        helm:
           valueFiles:
             - $values/argocd-cluster-secrets-values.yaml   #TODO      
      - repoURL: 'https://github.com/naren4b/naren4b-config.git'
        targetRevision: HEAD
        ref: values
      destination:
        server: '{{ "{{" }}server{{ "}}" }}'
        namespace: '{{ "{{" }}name{{ "}}" }}-zone-argocd'
      syncPolicy:
        automated:
           allowEmpty: true
           selfHeal: true
        syncOptions:
          - CreateNamespace=true        
