apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-app
  name: {{ .Values.name }}
spec:
  containers:
    - image: nginx
      name: {{ .Values.name }}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
